### PR TITLE
Docker image

### PR DESCRIPTION
**Pull request by interone-ms**
Hi,

I have created a Dockerfile that uses your recent addition of `pyinstaller` to produce a minmal-sized Docker image (~20 MB instead of ~140 MB).

Unfortunately I'm not experienced with GitHub Actions, but it should be possible for you to set up an automated Docker build of this image and a publish on Docker Hub.

### CODE REVIEW

**Comment by simonrob** [comment]
Thanks for the work on this, and for the pull request.

It's great to see a more efficient Docker setup for the proxy, but I'd prefer not to merge configurations for specific external container setups to avoid taking on the ongoing maintenance burden.

If you plan to keep it updated I am happy to link to your fork from the [related projects](https://github.com/simonrob/email-oauth2-proxy#related-projects-and-alternatives) section of the readme.

**Comment by ski7777** [comment]
Hey @simonrob,

I'd really like to continue on this approach. What do you want to merge this PR?
- autobuild with github workflow
- setting `local_address = 0.0.0.0` automatically for example by introducing a new cli argument

Is this enough or are there any other blocking points?

**Comment by moriahmorgan** [comment]
@ski7777  this has already been accomplished as seen in the readme. 

See this repo:

https://github.com/blacktirion/email-oauth2-proxy-docker

**Comment by ski7777** [comment]
yes, but this is a different project and only builds manually. My plan is to build on each push or tag . Additionally we could implement an automatic push to pypi

**Comment by simonrob** [comment]
I'm reluctant to take on the additional burden of maintaining a Docker configuration, since I don't use this myself.

The [repository](https://github.com/blacktirion/email-oauth2-proxy-docker) maintained by @blacktirion is, as explained above, essentially a ready-made version of this, and that is what I'd recommend at the moment.

The proxy is not updated especially often because it is essentially feature-complete, so I really wouldn't worry about not having the very latest commit.

**Pull request closed without merging**
